<?php

/**
 * @file
 * CSP Extras module hooks.
 */

/**
 * Implements hook_library_info_alter().
 */
function csp_extras_library_info_alter(&$libraries, $extension) {

  // Add module ajax.js to core library.
  if ($extension == 'core' && isset($libraries['drupal.ajax'])) {
    $path = '/' . \Drupal::service('extension.list.module')->getPath('csp_extras') . '/js/ajax.js';
    $libraries['drupal.ajax']['js'][$path] = [
      'version' => '1.13',
    ];
  }
}
