# Schema for the configuration files of the csp module.

csp.settings:
  type: config_object
  label: 'Content Security Policy Settings'
  mapping:
    enforce:
      type: boolean
      label: 'Enforce'
    report:
      type: mapping
      label: 'Reporting'
      mapping:
        handler:
          type: string
          label: 'Handler'
        options:
          type: csp.report-handler.[%parent.handler]

csp.report-handler.report-uri-com:
  type: mapping
  label: 'Report-URI.com'
  mapping:
    subdomain:
      type: string
      label: 'Subdomain'
csp.report-handler.uri:
  type: mapping
  label: 'URI'
  mapping:
    uri:
      type: uri
      label: 'URI'

