# Schema for the configuration files of the csp module.

csp.settings:
  type: config_object
  label: 'Content Security Policy Settings'
  mapping:
    enforce:
      type: boolean
      label: 'Enforce'
